@startuml
start;
->client calls via http;
:GameResource;
->delegates request to bean;
:GameBean;
->receives request from GameResource
and instantiates GamePersistor;
:GameCore;
->calls validator to validate request;
:GameValidator;
if(is valid?) then
    ->save to database;
    :GamePersistor;
    ->(Yes) save to database and
    send success message to client;
stop;
else
    ->(No) send error message to client;
stop;
@enduml
